# Generated by Django 4.2.3 on 2023-07-09 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='link',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('actual_url', models.TextField(default='')),
                ('short_url', models.URLField(blank=True, default=True)),
                ('hit_count', models.IntegerField(default=0)),
                ('expired', models.BooleanField(default=False)),
            ],
        ),
    ]
